## Dataset Overview

This dataset contains Amazon sales transaction data with 100,000 records and 20 features, representing customer orders, product details, and sales metrics.

It includes:
- Order details (OrderID, OrderDate)
- Customer information (CustomerID, CustomerName)
- Product details (ProductID, ProductName, Category, Brand)
- Sales metrics (Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount)
- Transaction details (PaymentMethod, OrderStatus)
- Location data (City, State, Country)
- Seller information (SellerID)

The dataset is suitable for analyzing sales performance, customer behavior, product trends, and regional insights.

## Business Understanding

The objective of this analysis is to answer key business questions:

- Which products and categories generate the most revenue
- Customer purchasing behavior
- Most popular payment methods
- Sales trends over time
- Regional performance (city/state/country)

This analysis will support data-driven decision-making for improving sales strategies and customer engagement.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv(r"C:\Users\ACER\Downloads\EDAproject\data\raw\Amazon.csv")

df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,31-01-2023,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,30-12-2023,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,10-05-2022,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,18-07-2023,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,04-02-2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [2]:
df.shape

(100000, 20)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  str
 1   OrderDate      100000 non-null  str
 2   CustomerID     100000 non-null  str
 3   CustomerName   100000 non-null  str
 4   ProductID      100000 non-null  str
 5   ProductName    100000 non-null  str
 6   Category       100000 non-null  str
 7   Brand          100000 non-null  str
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  str
 15  OrderStatus    100000 non-null  str
 16  City           100000 non-null  str
 17  State          100000 non-null  str
 18  Country        100000 non-null  str
 19  SellerID       100000 non-null  str
dtypes: float64(5), int64(1), str(14)
memory usage: 15.3 MB

In [4]:
df.describe()

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

In [5]:
df.nunique()

OrderID          100000
OrderDate          1825
CustomerID        43233
CustomerName        200
ProductID            50
ProductName          50
Category              6
Brand                10
Quantity              5
UnitPrice         48433
Discount              7
Tax               23002
ShippingCost       1501
TotalAmount       79208
PaymentMethod         6
OrderStatus           5
City                 20
State                13
Country               5
SellerID           1999
dtype: int64

In [6]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

## Data Quality Issues

1. The `OrderDate` column was initially in string format and has been converted to datetime for proper time-based analysis.
2. No missing values were found across any columns in the dataset, indicating complete data.
3. No duplicate records were detected, ensuring data uniqueness.
4. Some categorical columns such as `Category`, `Brand`, and `PaymentMethod` may require standardization (e.g., consistent naming formats), which will be handled in Day 2.
5. Numerical columns like `UnitPrice`, `Tax`, `ShippingCost`, and `TotalAmount` show a wide range of values, indicating potential presence of outliers. These will be analyzed and treated in Day 2.

Overall, the dataset is clean with no major structural issues, but requires further preprocessing for consistency and outlier handling.

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
num_cols = df.select_dtypes(include=['number']).columns
cat_cols = df.select_dtypes(include=['object','string']).columns

print("Numerical Columns:", num_cols)
print("Categorical Columns:", cat_cols)

Numerical Columns: Index(['Quantity', 'UnitPrice', 'Discount', 'Tax', 'ShippingCost',
       'TotalAmount'],
      dtype='str')
Categorical Columns: Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='str')

In [9]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"], dayfirst=True)

In [10]:
df["OrderDate"].describe()

count                        100000
mean     2022-06-30 23:55:49.439999
min             2020-01-01 00:00:00
25%             2021-04-01 00:00:00
50%             2022-07-01 00:00:00
75%             2023-09-29 00:00:00
max             2024-12-29 00:00:00
Name: OrderDate, dtype: object